### ISSUE TITLE
Update versionCode

### ISSUE THREAD

**Issue by krt16s** [indywidualny/FacebookLite#1]
While you have updated (and tagged) a couple of version (names), your versionCode is still at 1. The versionCode is an integer that is used to check for updates.

**Comment by indywidualny** [comment]
Thank you. I will remember to publish all the future versions the right way. So I suppose the latest commit is now treated like the very first version of the app. Not good but actually not so bad. v1.3.2 is the best one and the app should look like this from the beginning.

So to make things clear - If I push the code and change versionCode to higher integer, will F-Droid update my app?

**Comment by krt16s** [comment]
It was not set to auto-update (it is now), so yes: Update the VC and tag with the version name -- this should add the updated build to our queue.
