### ISSUE TITLE
feature request: choose the slide-menu bar side

### ISSUE THREAD

**Issue by cptMikky** [indywidualny/FacebookLite#10]
Hi, love the app but can't use it ergonomically since the side-slide menu is unreachable for my thumb when using the phone single-handedly. I'd suggest adding an option to app setting to choose which side(s) does the menu slide from.

It would also make sense for the menu button (hw or virtual) to open the menu as well. Currently, nothing happens when menu button is pressed.

cheers!

 -cM.

**Comment by indywidualny** [comment]
Thanks. I will think about it during next update :)
About menu button - it's deprecated. Most devices don't have it anymore - http://android-developers.blogspot.com/2012/01/say-goodbye-to-menu-button.html

**Comment by indywidualny** [comment]
It will still slide from the left but the gesture will work up to the half of the screen. So the menu will be easy to open.

**Comment by cptMikky** [comment]
I reserve my judgment until after I've tested this. Could be nice. May I ask why did you choose to go this way rather than allowing switching sides?

**Comment by indywidualny** [comment]
Easier :D I need to test it as well.
But maybe I will add switching instead. It's unstable now but it will finally work fine.

**Comment by indywidualny** [comment]
Ok. It's will be online tomorrow or on Monday. I mean possibility to change the side of the menu. I'm closing the issue.
