### ISSUE TITLE
No default time interval for notifications?

### ISSUE THREAD

**Issue by Croydon** [indywidualny/FacebookLite#13]
I'm just on my way to try the notifications, however, there is no (visible) default for the time interval.

By the way, when this function is working like expected, I will be finally able to delete the original Facebook app. Keep up the good work! :)

**Comment by indywidualny** [comment]
Default is 30 minutes. Sorry about that broken description. 
Notifications should work. It's well tested and when something is wrong it checks again up to 3 times.
Obviously only that list is checked - https://www.facebook.com/notifications

**Comment by indywidualny** [comment]
It's released now: https://github.com/indywidualny/FacebookLite/releases/tag/v1.7.1
