### ISSUE TITLE
Where to find app settings?

### ISSUE THREAD

**Issue by jwalantsoneji** [indywidualny/FacebookLite#15]
Not able to find app settings menu to try new notification support

**Comment by indywidualny** [comment]
Please take a look: https://youtu.be/m86OCpOCoSg
It's easy :) 

Have a nice day!

**Comment by jwalantsoneji** [comment]
Thanks.. just go to know there was navigation bar on the right foo :-)

Done.

**Comment by bengaskin** [comment]
Wow, cool, had no idea. Suggest this be more easily user discoverable. Perhaps a small message on startup "swipe sideways for settings". I bet 99% of users haven't found this menu
