### ISSUE TITLE
Phone Identity and Status permissions

### ISSUE THREAD

**Issue by krayon** [indywidualny/FacebookLite#17]
As per Issue #14 , phone identity and status permissions are requested. This appears to be due to the saxrssreader having a minSdkVersion of < 4:
> $ tail -2 app/manifest-merger-release-report.txt
> android:uses-permission#android.permission.READ_PHONE_STATE
> IMPLIED from AndroidManifest.xml:2:1 reason: nl.matshofman.saxrssreader has a targetSdkVersion < 4

A quick test changing minSdkVersion to 15 (that of the Facebook Lite app) removed this inherited requirement.

**Comment by krayon** [comment]
> diff --git a/saxrssreader/src/main/AndroidManifest.xml b/saxrssreader/src/main/AndroidManifest.xml
> index a360e1f..faf9342 100644
> --- a/saxrssreader/src/main/AndroidManifest.xml
> +++ b/saxrssreader/src/main/AndroidManifest.xml
> @@ -4,7 +4,7 @@
>      android:versionCode="1"
>      android:versionName="1.0" >
>  
> -    <uses-sdk android:minSdkVersion="1" />
> +    <uses-sdk android:minSdkVersion="15" />
>         <uses-permission android:name="android.permission.INTERNET" />
>         
>      <application></application>

**Comment by krayon** [comment]
```
diff --git a/saxrssreader/src/main/AndroidManifest.xml b/saxrssreader/src/main/AndroidManifest.xml
index a360e1f..faf9342 100644
--- a/saxrssreader/src/main/AndroidManifest.xml
+++ b/saxrssreader/src/main/AndroidManifest.xml
@@ -4,7 +4,7 @@
     android:versionCode="1"
     android:versionName="1.0" >
 
-    <uses-sdk android:minSdkVersion="1" />
+    <uses-sdk android:minSdkVersion="15" />
        <uses-permission android:name="android.permission.INTERNET" />
        
     <application></application>
```

**Comment by indywidualny** [comment]
Thanks! I will change it. I didn't have a clue why this permission is used. Now I can remove it. 

Good job! ;)

**Comment by indywidualny** [comment]
Done (https://github.com/indywidualny/FacebookLite/releases/tag/v1.7.6)
