### ISSUE TITLE
Question: Does this app put facebook in a privacy sandbox like Tinfoil does?

### ISSUE THREAD

**Issue by logos88** [indywidualny/FacebookLite#2]
Does this app put facebook in a privacy sandbox like Tinfoil does?

**Comment by indywidualny** [comment]
The app is independent. It has no access to your Internet browser, its cache, Web history etc. It also has no access to your location. All external links are opened outside the app, in your internet browser. The app uses its own cache and it is also possible to clear it to fully log out. So it keeps you protected.

It's basically a standalone Web browser with features which help you viewing Facebook mobile website only.

**Comment by logos88** [comment]
Oks, that sound great!! Thanks for anwsering!! I wish it would be something like this for my desktop computer too because is just what I was looking for :D
