### ISSUE TITLE
YouTube Videos

### ISSUE THREAD

**Issue by juzman** [indywidualny/FacebookLite#21]
I'm loving this application. The only issue I find is trying to share YouTube videos, there isn't any "preview". It just shares the actual youtu.be URL.

Is there any way to add this, or is it a limitation of the mobile view?

**Comment by indywidualny** [comment]
I'm really sorry but the app is just a simple wrapper. It displays https://m.facebook.com/ and when something is wrong I have no possibility to change it.

Maybe try again, please. I know that long urls don't have this problem. It's something wrong with (youtu.be) shortened urls.

**Comment by juzman** [comment]
Ah right, I noticed if I go to my profile first, then tap post it seems to attach preview. Not from the "what's on your mind" section at top. So can't really help that being the website.
