### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by juzman** [indywidualny/FacebookLite#22]
Whenever I try to share a post, and try and tag someone in it. I type @[name] yet nothing comes up to tag them.

**Comment by indywidualny** [comment]
I'm really sorry but the app is just a simple wrapper. It displays https://m.facebook.com/ and when something is wrong I have no possibility to change it.

**Comment by juzman** [comment]
Ah okay, I understand. That's okay, it's still an awesome app.

**Comment by indywidualny** [comment]
Thanks ;)
