### ISSUE TITLE
Contacts provider ?

### ISSUE THREAD

**Issue by bestouff** [indywidualny/FacebookLite#23]
It would be great if FB Lite could provide contacts to Android (especially for photos and birthdays), now that https://github.com/loadrunner/Facebook-Contact-Sync doesn't work anymore (v1 api closed).

**Comment by indywidualny** [comment]
Hi! I don't think it's possible. The main goal is to create a simple Facebook browser with notifications. I don't use Facebook API (just a Facebook Mobile website) and I would like to keep the app lightweight.

**Comment by bestouff** [comment]
Precisely, the API doesn't allow that anymore, would it be possible via some kind of screen scraping ?

**Comment by indywidualny** [comment]
I'm just a beginner but I don't think it's a good way of doing it and i don't think it's even possible. This app is mainly a WebView and it doesn't allow to do most of things ;(
