### ISSUE TITLE
Zoom out return position problem in CHAT.

### ISSUE THREAD

**Issue by michalpl7** [indywidualny/FacebookLite#26]
Hello,

app is great but I've found 1 annoying "bug". In CHAT if You move back to older messages and get message with few photos, zoom in to one of them and press close button then You go back to... end of conversation. So You have to go back all way again to see another photo, and over and over again that way...

Would be great if app remembers its position in chat.

Greetings,
Mike

**Comment by indywidualny** [comment]
I'm framing Facebook's mobile website so I cannot fix all the Facebook's bugs. It's the default behaviour of their mobile website and I cannot change it.
