### ISSUE TITLE
gingerbread support.

### ISSUE THREAD

**Issue by killoid** [indywidualny/FacebookLite#4]
hi,
is it possible for u to support gingerbread devices? i'd like to try it on my gb device too. it's fantastic! thanks.

**Comment by indywidualny** [comment]
https://www.dropbox.com/s/ifkmnz8dv8qwfvi/FbLite-1.2-GB.apk?dl=0

It's an old version but everything works fine. Have fun! But I'm not planning to provide support for Gingerbread.

Newer versions use features which are not compatible with Gingerbread and it's almost impossible (for me) to make a good GB version.

**Comment by killoid** [comment]
thanks for ur reply.
