### ISSUE TITLE
Unable to open links

### ISSUE THREAD

**Issue by 5n00p3r** [indywidualny/FacebookLite#5]
Every time I try to open a link, Facebook lite closes immediately without any errors.

**Comment by 5n00p3r** [comment]
Every time I try to open a link, Facebook lite closes immediately without any errors. Sorry for the "every" above :) just tapped the wrong button while typing.

**Comment by indywidualny** [comment]
Hi. It's strange. Could you tell me what android version do you use and give me some basic info about the device?

**Comment by 5n00p3r** [comment]
My device is a Samsung Galaxy GT-S7710 (XCOVER2 /Skomer) with Vanir AOSP Kitkat 4.4.4 running

**Comment by 5n00p3r** [comment]
I just installed the 1.4 Version from here. Previously I had the latest version from F-Droid 1.3.2. Unfortunately there is the same behavior: If I try to open a shared link, Facebook lite closes immediately. Opening embedded pictures causes opening a browser an shows that picture. This is fine I think.

**Comment by indywidualny** [comment]
I was analyzing the code and everything seems to be ok. I'm sorry but I really don't know what can cause this behavior. On all my devices and virtual devices it just works fine and I cannot reproduce the situation.

Does anyone have any ideas?

**Comment by 5n00p3r** [comment]
Hi. I'm still having this issue. Every time I try to open a shared link, Facebook lite closes immediately and I'm back on the home screen. Isn't there an option to make a debug log or something else like this?

**Comment by indywidualny** [comment]
Could you check it please?

https://dl.dropboxusercontent.com/u/13103071/temp/app-release1.apk
https://dl.dropboxusercontent.com/u/13103071/temp/app-release2.apk

I hope it's fixed.

**Comment by indywidualny** [comment]
I hope 1.5.0 doesn't have the problem. If so open new issue please.
