### ISSUE TITLE
problem with traslucent navbar

### ISSUE THREAD

**Issue by rebus007** [indywidualny/FacebookLite#7]
It's impossible to clik link on bottom of a page
http://s8.postimg.org/tw6sxejjp/Screenshot_2015_04_04_23_39_25.png

**Comment by indywidualny** [comment]
Rotate to horizontal please. Transparent Navbar just works that way. Sometimes you need to change orientation to click something unreachable at portrait.

I will try to add some padding in the future.

**Comment by indywidualny** [comment]
It's fixed in the latest version. Check out 1.5.0.
