### ISSUE TITLE
Features  request : option to start the application on the inbox link and option to share a link with the app

### ISSUE THREAD

**Issue by krz37** [indywidualny/FacebookLite#8]
Hi,
It would be nice to be able to start the app directly on inbox in order to avoid the Facebook wall ranking algorithm that make us all loose time by being distracted. I am sure not to be the only one to use Facebook for messages only :). 
Also another nice feature would be to be able to share a link or text from another app via the Android share menu. 
Thank you in advance!

**Comment by indywidualny** [comment]
I will think about widget icon allowing to open messages directly. Stay tuned. 

About sharing from another app -  I have no idea how to implement it for now :)

**Comment by krz37** [comment]
Nice thanks! Currently I cannot put any widget on my screen but let's see when it is released (using smart launcher and screen already full with weather and calendar)

**Comment by indywidualny** [comment]
https://github.com/indywidualny/FacebookLite/releases/tag/v1.6.2

Shortcut to open messages directly (find it at launcher -> widgets/shortcuts)

**Comment by krz37** [comment]
Thanks for your update :) 
In my case I get this issue though :
http://s22.postimg.org/vqhy889td/tmp_22060_Screenshot_2015_05_20_11_31_2317464496.png
I guess I should change my launcher at some point

**Comment by indywidualny** [comment]
Not good :( I just created a standard shortcut available since the very first Android version (1.0). It's not even a widget but some (new) launchers show it in the widget list. Does your launcher support adding shortcuts? It should be present there. Google Now Launcher shows it in the widget list anyway.

**Comment by krz37** [comment]
My mistake, it is in the shortcut section. Thanks a lot :)
